hostname = "imap.gmail.com"
username = "crispinstichart" # With or without the '@gmail.com'
password = "lolno"
port = 993


[[scripts]]
    name = "Test Script "
    interpreter = "python3.9"
    location  = "tests/test_echo.py"

# [[scripts]]
#     name = "blaze it"
#     location = "don't/care.exe"
