name: Codecov
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    services:
      greenmail:
        image: crispinstichart/email-liberator-greenmail-test:latest
        env:
          GREENMAIL_OPTS: '-Dgreenmail.setup.test.all -Dgreenmail.hostname=0.0.0.0 -Dgreenmail.auth.disabled -Dgreenmail.verbose'
        ports:
          - 3993:3993
          - 3025:3025
          - 3110:3110 
          - 3143:3143
          - 3465:3465
          - 3993:3993
          - 3995:3995
    steps:
      - uses: actions/checkout@v1
      - name: Add Trusted Root Certificate
        run: | 
          cp .github/greenmail.crt /usr/local/share/ca-certificates/
          update-ca-certificates
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - uses: actions-rs/cargo@v1
        continue-on-error: true
        with:
          command: test
          args: --all-features --no-fail-fast -- --test-threads=1
        env:
          LLVM_PROFILE_FILE: "email-liberator-%p-%m.profraw"
          CARGO_INCREMENTAL: '0'
          RUSTFLAGS: '-Cinstrument-coverage'
      - uses: actions-rs/grcov@v0.1
      - name: Upload to CodeCov
        uses: codecov/codecov-action@v1
        with: 
          files: coverage.json
