name: Codecov
on: [push, pull_request]
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    container: rustlang/rust:latest # nightly rust
    env: 
      RUSTFLAGS: "-Cinstrument-coverage"
      LLVM_PROFILE_FILE: "coverage-%p-%m.profraw"
    steps:
      - name: Fetch
        uses: actions/checkout@v2
      - name: Install Prerequsites
        run: |
          rustup component add llvm-tools-preview
          cargo install grcov
      - name: Run Tests
        run: cargo test
      - name: Generate Reports
        run: |
          grcov . --binary-path ./target/debug/ -s . -t covdir --branch --ignore-not-existing --ignore "*cargo*" -o coverage.json
      - name: Upload to CodeCov
        uses: codecov/codecov-action@v1
        with: 
          files: coverage.json