name: Codecov
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - uses: actions-rs/cargo@v1
        continue-on-error: true
        with:
          command: test
          args: --all-features --no-fail-fast --test-threads=1
        env:
          LLVM_PROFILE_FILE: "email-liberator-%p-%m.profraw"
          CARGO_INCREMENTAL: '0'
          RUSTFLAGS: '-Cinstrument-coverage'
      - uses: actions-rs/grcov@v0.1
      - name: Upload to CodeCov
        uses: codecov/codecov-action@v1
        with: 
          files: coverage.json